version: 2
jobs:
  build:
    working_directory: ~/bundlesize
    parallelism: 1
    docker:
      - image: node:7.10.0
    steps:
      - checkout
      - run:
          name: Install Deps
          command: npm install
      - run:
          name: Test
          command: npm run test
